name: Lint and Commit

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: astral-sh/ruff-action@v3
    - run: ruff check --fix
    - run: ruff format